### ISSUE TITLE
Goroutine leak in GS scheduling

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#1375]
#### Summary

There seems to be a goroutine leak in GS scheduling.

#### Steps to Reproduce

1. Start The Things Stack and let it run for a while
2. Run a pprof on goroutines

#### What do you see now?

<img width="656" alt="Screenshot 2019-09-23 at 15 20 54" src="https://user-images.githubusercontent.com/181308/65429038-c1495980-de15-11e9-9578-0e4f1168c0db.png">

<img width="825" alt="Screenshot 2019-09-23 at 15 20 10" src="https://user-images.githubusercontent.com/181308/65428975-a7a81200-de15-11e9-9a8d-614b4f89fb30.png">

#### What do you want to see instead?

I'd expect the number of goroutines to be more stable, and definitely not this many in GS scheduling GC.

#### Environment

e69e3e135

**Comment by johanstokking** [comment]
The problem is that the cancelable context is initiated in `io.NewConnection()`, while it has before been passed to `NewScheduler()`. So, on disconnect, the context that the scheduler used is not canceled.

Change the initialization order a bit. It's not just moving code because `NewConnection()` takes the scheduler. We may have `NewConnection()` instantiate the scheduler with the cancelable context, if that doesn't create nasty dependencies.

**Comment by KrishnaIyer** [comment]
@johanstokking : This is already fixed in `master` via my latest PR ([dc71f54](https://github.com/TheThingsNetwork/lorawan-stack/commit/dc71f540b328f9cb0e6ae5eba3c0586a3b8d51f8)).

**Comment by KrishnaIyer** [comment]
This can be closed once tested on the demo env.

**Comment by htdvisser** [comment]
This indeed seems to be resolved in 67cc2b31b
