### ISSUE TITLE
End Device Search

### ISSUE THREAD

**Issue by vsbandaru** [TheThingsNetwork/lorawan-stack#1654]
#### Summary
Search functionality in Console by DevEUI, DevID or Name, more fields could be added. 

#### Why do we need this?
Looking up device status to debug/monitor gets harder as the number of devices deployed reaches hundreds or thousands. Most organizations would follow a naming convention for the Device ID/Name and having the Search feature eases the management. 

#### What is already there? What do you see now?
No Search functionality available currently.

#### What is missing? What do you want to see?
A Search UI on the Applications page with the following fields

- Device ID
- Device Name
- Dev EUI
- and more if suggested by other users.

#### Environment
Console

#### How do you propose to implement this?
Implement a Search Header Section on **Applications** page.

#### Can you do this yourself and submit a Pull Request?
No

**Comment by kschiffer** [comment]
Related: https://github.com/TheThingsNetwork/lorawan-stack/issues/73

**Comment by htdvisser** [comment]
API definition for EndDeviceRegistrySearch: https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.3.1/api/search_services.proto#L84-L115

That API allows you to (substring) search by

- ID
- Friendly Name
- Description
- Attributes
- EUI
- DevAddr (*)

A simple version of this API can be implemented on the Identity Server. This implementation would be able to search by all above fields, except DevAddr (the DevAddr is owned by the Network Server, not the Identity Server). I can work on that.

This would be simpler than resolving #73, because we can already scope the search to the Application ID that we know the caller has rights on.

Let's separate the issues (I'll remove EndDevice search form #73) and focus on this one (#1654) first.

**Comment by kschiffer** [comment]
Closing this, since it intersects with #1803. Please continue discussion there if need be.
The issue has a PR and should be resolved soon.
