### ISSUE TITLE
LoRa Cloud DAS configuration per application with URL config

### ISSUE THREAD

**Issue by Oliv4945** [TheThingsNetwork/lorawan-stack#2412]
#### Summary
LoRaCloud users should be able to select their own DAS server URL as it will not always be `https://das.loracloud.com`

#### How do you propose to implement this?
Add a `das-server-url` option taking and URL input

#### Can you do this yourself and submit a Pull Request?
Seems difficult, but maybe if I am helped with the steps to do it

**Comment by johanstokking** [comment]
@Oliv4945 what is the scope of this; per-integration? Not per device I hope?

**Comment by johanstokking** [comment]
Adding `compat/api` for the users to customize the URL.

@adriansmares I'm quite sure the PR needs `bump/minor` as an old CLI or Console may mess up the new settings

**Comment by adriansmares** [comment]
Application packages have their configuration stored on a per-device basis (due to the nature of the FPort identifiers), so this would be indeed per-device. Nonetheless, the configuration is easily loaded through CLI so mass-provisioning this is fine.

Regarding the CLI question - actually settings are loaded as JSON (we use `proto.Struct`), so old CLI's won't break this, and we can ensure that missing values default to the preconfigured default.

**Comment by johanstokking** [comment]
OK great!

**Comment by Oliv4945** [comment]
@johanstokking @adriansmares As discussed during TTN conference application packages as per-devices, but it would be great to be able to have a configuration per application like the payload decoder.
