### ISSUE TITLE
ADR datarate calculation is based only on the ADR uplink requests

### ISSUE THREAD

**Issue by pdubois22** [TheThingsNetwork/lorawan-stack#272]
**Summary:** 
IHMO, ADR calc and especially margin calculation should be based on all last received Uplink

**Steps to Reproduce:** 

**What do you see now?**
pkg/networkserver/adr.go

max SNR is calculated on RecentADRUplinks. Should be RecentUplinks ?

https://github.com/TheThingsNetwork/lorawan-stack/blob/68e50c3c45dd1f848747ef00d9165e3e113a09fe/pkg/networkserver/adr.go#L89

```
ups := dev.RecentADRUplinks
	if len(ups) == 0 {
		return nil
	}

	maxSNR := ups[0].RxMetadata[0].SNR
	for _, up := range ups {
		for _, md := range up.RxMetadata {
			if md.SNR > maxSNR {
				maxSNR = md.SNR
			}
		}
	}
```

**What do you want to see instead?**
ADR based on all recent uplinks.

**How do you propose to implement this?**
change adr.go 

**Environment:**
master

**What can you do yourself and what do you need help with?**

**Comment by htdvisser** [comment]
This is as intended. When a device detects that it has stable radio conditions, it sets the ADR bit. From that moment on, we start collecting `RecentADRUplinks`. If the device detects that radio conditions are not stable (perhaps because it is moving), the device unsets the ADR bit, and we clear `RecentADRUplinks`. We still keep `RecentUplinks` for other purposes.

The ADR algorithm only considers uplinks that were sent under stable radio conditions, so it uses `RecentADRUplinks`.
