### ISSUE TITLE
Unable to share the data between MQTT pub/sub clients

### ISSUE THREAD

**Issue by vvksahoo** [TheThingsNetwork/lorawan-stack#2888]
#### Summary

I have created a gateway ([Adding Gateways in the Console](https://enterprise.thethingsstack.io/v3.8.4/getting-started/console/create-gateway/)).
Trying to interact with gateway via MQTT.  But data is not able to shared between MQTT pub and sub clients.
...

#### Steps to Reproduce

1. Using Gateway Server address as mqtt ip address, port is 1882, username is<gw-id@tenant-id> and password as API key.
2. 
```
mosquitto_sub -h <gateway server address> -p 1882 -t 'v3/gwID/down' -u <gw-id@tenant-id> -P <API-KEY>
```
Using above MQTT SUB client, able to connect to the gateway. I can see that on latest events window.
3. 

```
mosquitto_pub -h <gateway server address> -p 1882 -t 'v3/gwID/down' -m 'Hello Gateway' -u <gw-id@tenant-id> -P <API-KEY>
```
Using above MQTT PUB client, able to connect to the gateway and send the data. But the other hand  MQTT SUB client is not received any data.

#### Environment

v3.8.5
windows
Chrome browser
...

**Comment by KrishnaIyer** [comment]
The MQTT broker on the GS is not general purpose but is used for MQTT gateway connections.
`v3/gwID/down` is a downstream message (i.e., stack -> gateway). Sending data on it will not result in anything. 
We have an issue for documenting the Gateway MQTT messages: #2743 
Please follow that so that you know when it's done.
