### ISSUE TITLE
Improving the documentation sidebar appearance

### ISSUE THREAD

**Issue by nejraselimovic** [TheThingsNetwork/lorawan-stack#3112]
#### Summary
While navigating through the documentation site, subsections of the non-selected parent section should be hidden, while the subsections of the selected parent should be visible.

#### Why do we need this ?
As documentation grows, the sidebar navigation gets messier and this could help improving it.

#### What is already there? What do you see now?
We have this:
![sidebar](https://user-images.githubusercontent.com/65215579/90778280-b97f8700-e2fc-11ea-8338-5d2d89a4d1b3.png)

#### Can you do this yourself and submit a Pull Request?
@pgalic96 @kschiffer can you help?

**Comment by pierrephz** [comment]
I think this sidebar is messy also because of the display and **we could improve it by doing two things** (in addition to Nejra comment above):

<img width="2032" alt="Screenshot 2020-08-21 at 12 05 03" src="https://user-images.githubusercontent.com/26456318/90880187-59461f00-e3a8-11ea-883a-a581eefea79b.png">

- **Make it as a fixed side div that we can scroll** (red notes on the screenshot above)
Now, you have to scroll the entire page to scroll le sidebar. This is too much

- **Create white space between this sidebar and the content** (orange notes on the screenshot above)
Now we feel oppressed. This is a documentation page, which is kind of heavy content, so user should have some space to breath

**Comment by johanstokking** [comment]
Is this actionable enough? Who is picking this up?

**Comment by nejraselimovic** [comment]
> Is this actionable enough? Who is picking this up?

Did I assign the right people here?

**Comment by johanstokking** [comment]
With three people assigned, who's responsible and who does what?

**Comment by nejraselimovic** [comment]
> With three people assigned, who's responsible and who does what?

It's my mistake because I wasn't sure who can actually pull this off and ofc this discussion could be avoided if I asked who can do it before assigning them (will do in the future). I can help, but I don't know how to do this by myself. @kschiffer @pgalic96 can someone pick this one up please?

**Comment by kschiffer** [comment]
Not your mistake. It's ok to assign more people when in doubt and it's the assignee's responsibility to narrow things down. I would say that @benolayinka is best for implementing this. It should be a relatively simple CSS job.

@benolayinka can you confirm and reassign if necessary then?

**Comment by benolayinka** [comment]
Moved to https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/97
