### ISSUE TITLE
Registries allow creation of devices for non-existent applications

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#346]
**Summary:** 

Registries allow creation of devices for non-existent applications

**Steps to Reproduce:** 

1. Initialize stack
2. Start stack
3. `go run ./cmd/ttn-lw-cli login && go run ./cmd/ttn-lw-cli end-devices create --application-id test-app  --device-id test-sim --dev-eui 4200000000000000 --join-eui 4200000000000000 --frequency_plan_id EU_863_870 --root_keys.app_key.key 42000000000000000000000000000000 --lorawan_phy_version "1.0.2-b" --lorawan-version '1.0.2' --supports_class_c && go run ./cmd/ttn-lw-cli app create test-app --user-id admin`

**What do you see now?**

Successful creation of the device

**What do you want to see instead?**

Error stating that application does not exist

**How do you propose to implement this?**

Not sure. @johanstokking ?

**Environment:**

Any

**What can you do yourself and what do you need help with?**

I can go on holiday and let someone else fix it

**Comment by johanstokking** [comment]
Digged into this a bit. The reason all application rights are given is because the user is admin.

However, I don't think that IS should issue all rights for a non-existing entity, regardless of being admin.

**How do you propose to implement this?**

In `(is *IdentityServer) ApplicationRights()` (and for other entities), check existence and apply universal rights for entities only when the entity exist.

My take is that we should not issue singular rights (i.e. `RIGHT_APPLICATION_*`) when the entity doesn't exist. But do issue plural rights (i.e. `RIGHT_APPLICATIONS_*`) like we already do. This way, admins can create any application, but not set orphan devices in non-existent applications.
