### ISSUE TITLE
Option to modify the DR that NS sends in `LinkADRReq`

### ISSUE THREAD

**Issue by ymgupta** [TheThingsNetwork/lorawan-stack#3564]
#### Summary
Capability for Network Server to not alter the data rate in LinkADR is only present in LoRaWAN versions higher than 1.0.4. At this point of time, it is not possible to modify the DR that NS sends in `LinkADRReq`

#### Why do we need this?
ADR might be aggressive for a few deployments and might result in packet loss.

#### What is already there? What do you see now?
- Currently, the uplink data rate is decided and altered by NS via LinkADRReq
- We can only fetch the DR set by the LinkADRReq using the following commands but can’t modify
```
ttn-lw-cli end-devices get <app-id> <dev-id> --mac-state.current-parameters.adr-data-rate-index
ttn-lw-cli end-devices get <app-id> <dev-id> --mac-state.desired-parameters.adr-data-rate-index

```
#### What is missing? What do you want to see?
- An option to alter the uplink DataRate from the Network Server
- An option/a CLI command to change the DR sent as part of LinkADRReq using which the uplink DR can be adjusted without the need for physical access to the device.

#### Environment
TTES V3.10.3 CH

#### How do you propose to implement this?

...

#### How do you propose to test this?

...

#### Can you do this yourself and submit a Pull Request?
No. @rvolosatovs

**Comment by baranisrc** [comment]
We can help you test it with our MeteoHelix weather stations [https://www.baranidesign.com/meteohelix-pro-weather-station](url) as we requested this feature.  It is quite urgent for us to implement as it will enable us to cusomize ADR individually based on device performance and local RF noise levels for high reliability data tramsmissiona which is critical to meteorological applications.  Feel free to email/message me so that I can organize testing for you with our devices. BR, Jan Barani
