### ISSUE TITLE
Allow restoring and purging soft-deleted entities in the Console

### ISSUE THREAD

**Issue by bafonins** [TheThingsNetwork/lorawan-stack#3585]
#### Summary

With https://github.com/TheThingsNetwork/lorawan-stack/pull/3467 we allow deleting entities and releasing their ids. We should add this to the Console.

#### Why do we need this?

Allow the user to chose between soft and hard deletion.

#### What is already there? What do you see now?

Delete modal
<img width="623" alt="Screenshot 2020-12-10 at 16 48 14" src="https://user-images.githubusercontent.com/16374166/101787253-8eb57a80-3b07-11eb-8ff2-0edfa8ce2bc4.png">

that uses `Delete` RPC's for each entity.

#### What is missing? What do you want to see?

Option to perform hard deletion.

#### Environment

v3.10.4

#### How do you propose to implement this?

IMO, we can extend the existing modal with `Release entity ID` checkbox that initially is unchecked.
cc @kschiffer 

#### How do you propose to test this?

e2e tests and manual testing

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by kschiffer** [comment]
Here's how I think this should work (for applications as an example):

1.  The delete action in the Console should always trigger the purge endpoint.
2.  In case the application is "pristine", e.g. has no devices, and other entities associated whatsoever, we can keep the modal behavior as it is right now.
3.  In case the application is not "pristine", the modal should be updated informing that all devices, webhooks, API keys and other data associated with the application are deleted irretrievably. Additionally, for such high-danger actions, we should add a "type name of entity" confirmation (similar to how deleting repository works on Github).

**Comment by johanstokking** [comment]
References #3739

**Comment by kschiffer** [comment]
I suggest to reconsider the milestone/prioritization since we now release entity IDs automatically when deleting via the Console. I think it's a good idea now to update the deletion flow as mentioned in my comment above.

Adding to 3.:

We should make a typed confirmation for applications, gateways and users/organizations.

**Comment by htdvisser** [comment]
Pushing this to v3.13.2. I don't think @bafonins is going to be working on this on his day off, so this definitely won't make it to today's deadline for v3.13.1.

**Comment by htdvisser** [comment]
Re-opening this, since I don't think the permanent delete should be the default for admins. Security/privacy guarantees go out of the window when releasing entity IDs. If someone else registers a deleted ID, they may suddenly have access to stored data of the old entity. This is not something we can fix without breaking V3 compatibility, so we should try not to release IDs until V4 at least.

I propose that we change this to let admins toggle between the default soft-delete and the permanent delete.

**Comment by htdvisser** [comment]
@bafonins please put this in an appropriate milestone, depending on your availability.

**Comment by bafonins** [comment]
@kschiffer What should be changed in the UI?

**Comment by kschiffer** [comment]
Let's have two buttons then for admins next to each other in the general settings panel then `Soft delete {entity}` and `Hard delete {entity}`.

**Comment by kschiffer** [comment]
@htdvisser so as far as I understand, we can provide this option for admin users when deleting an entity, but do not make it a default. Basically it would mean adding a checkbox to the deletion modal that would change the operation to purge, together with a tooltip explaining the implications for security:

```
Releasing the entity IDs will make it possible to register a new entity with the same ID. Note that this could potentially generate security issues when  such device is accidentally or purposefully created from a third party, since it will effectively take-over the security context of the deleted device.
```

Please confirm.

**Comment by htdvisser** [comment]
Originally the idea was that "purge" would only be available for deleted entities (in the Console: from the "list deleted" views), and only after a some cooldown period, but that idea got lost along the way.

I think we need to be even more clear about what the "purge" checkbox does so that users understand what is (and isn't) going to happen.

Purging an (entity)...

- will **permanently** delete the (entity)
- will **permanently** delete collaborator rights related to the entity (does not apply to users, those don't have collaborators)
- will **permanently** delete API keys related to the entity (does not apply to OAuth clients, those don't have API keys)
- will **not** delete stored data in routing clusters (only in the Identity Server)
- will **not** delete stored events for the (entity)
- will **not** delete information stored in Packet Broker (applies to gateways)
- will **not** delete stored data in the storage integration (applies to applications)
- will **not** delete stored data in external integrations (applies to applications)
- will release the ID of the (entity) for re-use, which **may give other users access to historical data** of the (entity) if they register one with the same ID

**Comment by kschiffer** [comment]
Ok so let's do the following:

*   Add the purge checkbox for admins as discussed above
    *   We need to make sure that the checkbox is recognized correctly (and not mistaken for a confirmation checkbox)
    *   Please use a title for this checkbox: `Entity purge (admin only)`
    *   Use `Also release entity IDs (purge)` as checkbox label
    *   When checking the checkbox, display a warning notification: (also do not use a tooltip, like initially suggested)

> ```
> Releasing the entity IDs will make it possible to register a new entity with the same ID. Note that this <b>irreversible</b> and may lead to <b>other users gaining access to historical data of the entity if they register an entity with the same ID</b> . Please make sure you understand the implications of purging as described here [https://www.thethingsindustries.com/docs/reference/purge/].
> ```

*   Let's go full circle and add that initial idea in the entity tables where there will be a new tab (visible for admins only) that shows deleted entities and displays a purge (and restore) button on the table row to purge individual entities.

@htdvisser iirc, you made a draft PR that does the deleted entity table. I couldn't immediately find it. Can you link it here, so @bafonins can use it as reference?

**Comment by bafonins** [comment]
Reopening this issue to keep track of the deleted entity tables as mentioned in https://github.com/TheThingsNetwork/lorawan-stack/issues/3585#issuecomment-880683737

**Comment by benolayinka** [comment]
How is hard delete done in the console now? I'd like to add a screenshot to https://www.thethingsindustries.com/docs/reference/purge/

**Comment by bafonins** [comment]
@benolayinka Currently, entity deletion works as follows:

<img width="700" alt="Screenshot 2021-08-10 at 13 53 08" src="https://user-images.githubusercontent.com/16374166/128854499-70bc89c0-7d07-4729-b053-36b8197bfddf.png">
<img width="700" alt="Screenshot 2021-08-10 at 13 53 00" src="https://user-images.githubusercontent.com/16374166/128854503-8e2dd9ac-74d4-46cb-bace-ed1d911a69d2.png">


1. If the user is admin then
* there is an option to perform hard deletion (can reuse entity id)
* use regular soft deletion (cannot reuse entity id)
2. If the user is not admin, then there only one option: regular soft deletion

Also, see screenshots
