### ISSUE TITLE
App Key text field is too narrow

### ISSUE THREAD

**Issue by eggfriedrice** [TheThingsNetwork/lorawan-stack#3784]
#### Summary
When registering a new device the App Key field in the form is too narrow to show the whole key, the last byte overflows. There is no indication that there's another couple of characters off to the right of the field. This is causing trouble for users when they generate a key and copy it out as they're missing off the last byte.
...

#### Steps to Reproduce

1. Start to register a new device
2. Run through the first step to select a device template
3. Click the generate app key button next to the field

---

#### What do you see now?
---
You'll get something like this:

![Register-end-device-al-thing-The-Things-Network](https://user-images.githubusercontent.com/1146915/107621744-a23ba980-6c4e-11eb-89d1-1f4eb70144a5.png)
---
Note that there's a "hidden" final byte at the right:
![extra byte](https://user-images.githubusercontent.com/1146915/107622085-3c035680-6c4f-11eb-8a53-fd92b70079ab.png)

...

#### What do you want to see instead?
A slightly wider text box! This seems to happen at all screen sizes.

...

#### Environment
Tested in Chrome/Linux with public v3 and private instances

**Comment by bafonins** [comment]
Reopening this since https://github.com/TheThingsNetwork/lorawan-stack/pull/3792 doesnt solve the issue for Safari:

<img width="345" alt="Screenshot 2021-02-19 at 14 45 37" src="https://user-images.githubusercontent.com/16374166/108506627-c425d380-72c1-11eb-94e7-b5001667c934.png">
<img width="345" alt="Screenshot 2021-02-19 at 14 45 41" src="https://user-images.githubusercontent.com/16374166/108506630-c4be6a00-72c1-11eb-88f9-030f411a814f.png">

<img width="506" alt="Screenshot 2021-02-19 at 14 50 22" src="https://user-images.githubusercontent.com/16374166/108506635-c8ea8780-72c1-11eb-90a5-268454ad79d9.png">
<img width="506" alt="Screenshot 2021-02-19 at 14 50 29" src="https://user-images.githubusercontent.com/16374166/108506638-c9831e00-72c1-11eb-89c0-505e0e7b9837.png">
