### ISSUE TITLE
Vendor specified JS decoder ignore or override or petition for inappropriate use for removal

### ISSUE THREAD

**Issue by nejraselimovic** [TheThingsNetwork/lorawan-stack#4098]
#### Summary
Arduino MKR WAN 1310 has a JS decoder in the repository for a tutorial.

This appears in the background like a ghost entry that now has to be overridden.

The application shows None for the Uplink decoder.

Saving as None doesn't turn off the decoder. Saving as Repository leaves it working. Changing to None still doesn't turn it off.

#### What do you see now?
Bizzare entries in the console log about an LED state that have nothing to do with the application, one very confused client on Zoom.

#### What do you want to see instead?
Nothing, zip, nada, zero, zilch - ie, no decoding unless I say so.

Strongly discourage generic devices having random JS put in to the device repository.

But for those times when there is a more use case appropriate for a JS decoder, some indication that one is present in the back-end that you weren't aware of and/or ability to copy it for editing at the application or device level

#### How do you propose to implement this?
Not sure

#### Can you do this yourself and submit a Pull Request?
Hopefully @karlsoderby can address this issue related to the MKR WAN. I could do it but I hate to think how you'll audit a PR from a third party.

Original issue: https://github.com/TheThingsNetwork/lorawan-devices/issues/139

**Comment by neoaggelos** [comment]
References #4081

**Comment by neoaggelos** [comment]
The behaviour with the payload formatters is as follows:

- Applications can have a default payload formatter
- End devices can have a payload formatter overriding the one set in the application level.

Just tested with latest version:

| Application Formatter | Device Formatter | Result |
| --- | --- | ---- |
| Repository | Repository | The codecs from the device repository are used (if any) |
| Repository | None | No codecs are used |
| Repository | Use application payload formatter | The codecs from the device repository are used (if any) |
| None | Repository | The codecs from the device repository are used (if any) |
| None | None | No codecs are used |
| None | Use application payload formatter | No codecs are used |

In any case, setting the device payload formatters to None will disable the use of codecs from the device repository.

Improving the UX to make sure that this does not cause confusion to users is tracked in #4081.

I do second that adding payload formatters for "generic" devices (like the one mentioned in the issue description, or maybe even The Things Uno), is not a good choice because it inevitably leads to issues like this, but this is a discussion for the lorawan-devices repository and not The Things Stack.
