### ISSUE TITLE
Can't use /oauth/logout request for federated logout

### ISSUE THREAD

**Issue by romach** [TheThingsNetwork/lorawan-stack#4516]
#### Summary

I'm trying to use `https://eu1.cloud.thethings.network/oauth/logout?access_token_id=<ACCESS_TOKEN>` request to logout from all sessions. But, instead, I'm logged out only from the current session.

#### Steps to Reproduce

1. Login to console using https://eu1.cloud.thethings.network/oauth/login url
2. Get access token using Oauth flow (https://www.thethingsindustries.com/docs/reference/api/authentication/#oauth-access-tokens)
3. Make a request with HTTP client (Postman or curl) to `https://eu1.cloud.thethings.network/oauth/logout?access_token_id=<ACCESS_TOKEN>` with access token from step 2. 
4. Try to login to https://eu1.cloud.thethings.network/console/

#### What do you see now?

The user is logged in to Console

#### What do you want to see instead?

The log-in form should be opened.
User need to submit credentials to log in.

#### Environment

...

#### How do you propose to implement this?

...

#### How do you propose to test this?

...

#### Can you do this yourself and submit a Pull Request?

...

**Comment by kschiffer** [comment]
Hi @romach !

It is true that the endpoint you describe only deletes the access token and terminates the exact session that it was associated with. We cannot terminate all sessions by default because that could affect access to other clients on other machines as well, which is not desired. If you want to have more control over sessions and access tokens, you can use these endpoints:

`GET /api/v3/users/{user_id}/sessions` new since v3.14.0

`DELETE /api/v3/users/{user_id}/sessions/{session_id}` new since v3.14.0

and for the access tokens;

`GET /users/{user_id}/authorizations/{client_id}/tokens`

`DELETE /users/{user_id}/authorizations/{client_id}/tokens/{id}`
