### ISSUE TITLE
Cancelling The Things ID login leads to "Forbidden" error

### ISSUE THREAD

**Issue by nejraselimovic** [TheThingsNetwork/lorawan-stack#4564]
#### Summary
Cancelling login via The Things ID leads to "Forbidden" error

#### What do you see now?
![1](https://user-images.githubusercontent.com/65215579/131509248-20d6eae5-588b-497a-ac3b-159b0b2c25b9.png)

If you click **Cancel**, you get:
![2](https://user-images.githubusercontent.com/65215579/131509261-605659d0-e254-4c81-a611-8d4e2c0bfe9b.png)

#### What do you want to see instead?
Instead of this error, a user should probably be redirected to the login page

#### Environment
TTS Community Edition

#### Can you do this yourself and submit a Pull Request?
@kschiffer?

**Comment by kschiffer** [comment]
So I've spent some time looking into other services that use OpenID Connect (our auth flow in TTID) and from what I can see, Google, Facebook, and Apple do not even provide a cancel option when using their services to login. This makes me wonder if we even need such functionality when the user can just as well use the browser's back button.

Technically, the only difference I would see is that the state cookie would remain stored but I don't believe this is problematic, since every newly initiated login would invalidate the cookie anyway.

UX-wise I don't believe removing the cancel button would be problematic in any way.

**Comment by kschiffer** [comment]
I'd like to open this up for discussion. @htdvisser @bafonins @NicolasMrad

**Comment by NicolasMrad** [comment]
I just visited random websites to check the log-in process and none of them have a cancel button, so in my opinion users presses or going back is sufficient without having a cancel button.

**Comment by htdvisser** [comment]
I don't think a cancel button makes sense when a user _actively_ tries to login. However, if a user gets automatically redirected to TTID, I think the UI should show them that they have a choice between continuing and cancelling. Especially if pressing "back" simply redirects them to the login page again, I think it's better to explicitly tell the OAuth client "no".

**Comment by kschiffer** [comment]
What should happen then, upon clicking cancel?

**Comment by kschiffer** [comment]
See also https://discuss.thethingsindustries.com/t/ttsce-and-ttid-login-ux/655

**Comment by htdvisser** [comment]
Conclusion after discussion: we just need to catch the error, show a nicer message and a button to the solution (go to login page)
