### ISSUE TITLE
Pick up LoRa Cloud GNSS data from payload formatter field

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/lorawan-stack#4630]
#### Summary

We should ask device makers to break out Semtech GNSS data for the LR1110 in a payload formatter, and then pick it up in the LoRa Cloud integration by looking for that key

#### Why do we need this?

- The GNSS data does not come in uplinks in a standardized form. On the yabby edge, for example, it is contained in variable length wifi/gnss uplinks as the last 8 bytes. This needs to be defined in a payload formatter
- By looking for that key, we can stop doing unnecessary LoRa Cloud requests for devices with no GNSS data (currently, enabling the LoRa Cloud integration creates an error on every uplink)

#### What is already there? What do you see now?

When the LoRa Cloud integration is enabled for an application, all uplinks are forwarded to LoRa Cloud regardless of whether they contain valid gnss data

#### What is missing? What do you want to see?

Only make LoRa cloud requests based on the presence of a gnss data key in the decoded output

#### Can you do this yourself and submit a Pull Request?

@adriansmares

**Comment by jpmeijers** [comment]
This sounds like the type of logic that could be offloaded to the application payload parser:
https://github.com/TheThingsNetwork/lorawan-application-payload

**Comment by benolayinka** [comment]
> This sounds like the type of logic that could be offloaded to the application payload parser:
> https://github.com/TheThingsNetwork/lorawan-application-payload

What is it? Docs dont say

**Comment by johanstokking** [comment]
So the suggestion is for payload decoders to signal that there is GNSS data, and then let the LoRa Cloud application package check that value as a filter.

Does that mean that for each and every end device that may send GNSS values, we need to make sure that signal field is in the decoded payload?

Why does LoRa Cloud just not care about missing GNSS data?

LoRa Cloud is only considering FRMPayload right, not decoded payload?

**Comment by adriansmares** [comment]
This is more about Geolocation Services, rather than Device and Application Services.

While DAS will indeed have its own protocol that is opaque and does not need any external help in order to process / transmit the GNSS payload, this is not the case for GLS.

GLS is more barebones - you give it a GNSS payload, and it gives you back the location of the tracker. How thay payload reaches the API is not specified. For all that matters, the GNSS payload may travel via SMS or email between the device and the GLS API.

The current GLS GNSS mode takes the frame payload and simply sends it to GLS. The problem is that not all devices do this (raw GNSS payload as frame payload) - for example the device in the original post which does have some more proprietary binary around the GNSS payload.

The proposal here is to allow the AS to look at the decoded payload, and if a GNSS-like field is found to send that to GLS (instead of the whole frame). This is consistent with how the WiFi mode works - we expect the BSSIDs and RSSIs to have a specific format in the decoded payload, but its up to the formatter to get them from the frame.

**Comment by johanstokking** [comment]
OK, I didn't realize this is Geolocation and not DAS, thanks for clearing that up.

> and if a GNSS-like field is found to send that to GLS (instead of the whole frame)

And what if it's not there?

**Comment by adriansmares** [comment]
> And what if it's not there?

I would argue that the GLS request should not be done - then the order is:
- If no decoded payload is available, send the full frame.
- If the decoded payload is available, and there is no GNSS payload, do nothing.
- If the decoded payload is available, and there is a GNSS payload, send that.

**Comment by johanstokking** [comment]
OK. And I'm presuming that this aligns with the WiFi lookup, right?

**Comment by adriansmares** [comment]
> OK. And I'm presuming that this aligns with the WiFi lookup, right?

Indeed, and maybe we can move that to https://github.com/TheThingsNetwork/lorawan-application-payload too.

**Comment by benolayinka** [comment]
> And what if it's not there?

Currently, turning on GLS for an application performs GLS lookup for every device in the application, and produces an error in the console for every uplink if the payload is not raw GNSS data (which it almost never is). This would also prevent GLS calls for example for devices without LR1110 modems, and for all devices which don't have properly decoded LR1110 GNSS data.

**Comment by htdvisser** [comment]
Doesn't look like this is going to get finished for v3.17.0, so pushing to v3.17.1.

@NicolasMrad: This has been pushed forward since October, so I think we should re-evaluate the priority.
