### ISSUE TITLE
Certain configuration values are ignored

### ISSUE THREAD

**Issue by michalborkowski96** [TheThingsNetwork/lorawan-stack#4764]
#### Summary
In the Dockerfile we set the following environmental variables:

```
TTN_LW_BLOB_LOCAL_DIRECTORY
TTN_LW_IS_DATABASE_URI
TTN_LW_REDIS_ADDRESS
TTN_LW_HEALTHCHECK_URL
```

Since environmental variables take precedence over configuration file, if someone redefines them in the config file, these values will be ignored.

#### Steps to Reproduce
1. Add `is: database-uri` to the config file
2. Start the stack

#### What do you see now?
The value is ignored

#### What do you want to see instead?
The value from the config file should be used

#### Environment
docker compose

#### How do you propose to implement this?
In the Dockerfile, instead of running the stack, we could run a script that checks if certain configuration options are set in either config file or environmental variables, if not then set them in environmental variables, then it runs the stack.

#### How do you propose to test this?
Run with non-default `is: database-uri`

#### Can you do this yourself and submit a Pull Request?
Yes

@KrishnaIyer please provide feedback on the suggested solution

**Comment by KrishnaIyer** [comment]
@htdvisser we discussed this in the context of `lorawan-stack-migrate`. Does env take precedence over config?

I think @michalborkowski96's suggestion of running a script makes sense. What do you think?

**Comment by htdvisser** [comment]
Config precedence is FLAGS > ENV > FILE.

The problem is that somewhere in the past we decided to set environment in the Dockerfile. We shouldn't have done that, but if we remove it now, we may break some old Docker-based deployments (that didn't have the `TTN_LW_IS_DATABASE_URI` configured in docker-compose). So this would technically be a breaking change that requires a major version bump.

**Comment by michalborkowski96** [comment]
@htdvisser 

I think you misunderstood what I wrote.

The only broken deployments would be these that set `is: database-uri` in config, but rely on this config being ignored.

**Comment by htdvisser** [comment]
Okay, so what you're proposing is to remove the `ENV` from `Dockerfile`, and instead create a script that only sets those ENV if nothing else is configured?

This may get a bit complicated to do in a script, because there's a lot of logic in `ttn-lw-*` for config search paths, merging the file, env and flags, etc. Perhaps we can modify `ttn-lw-* config` commands to return a list of only explicitly configured options (so that the script won't get confused by defaults)?

**Comment by michalborkowski96** [comment]
> Perhaps we can modify ttn-lw-* config commands to return a list of only explicitly configured options (so that the script won't get confused by defaults)?

Sounds like a good idea

**Comment by michalborkowski96** [comment]
https://github.com/TheThingsNetwork/lorawan-stack/pull/4800
