### ISSUE TITLE
Console > Applications > Live data - must show best SNR/RSSI pair instead of only values from first gateway

### ISSUE THREAD

**Issue by lnlp** [TheThingsNetwork/lorawan-stack#4846]
#### Summary
In 'Console > Applications > _application_ > Live data' entries, SNR and RSSI values are displayed.
Currently these SNR and RSSI values are taken from the first gateway listed in the JSON data which makes no sense.

When an uplink is received by multiple gateways, always displaying SNR and RSSI values only from the first gateway makes no sense. From application perspective this is not representative for the signal quality of the uplink message received by the application.

One usually wants to know how well the uplink message was received. When the message was received by multiple gateways this means: the best SNR/RSSI values pair from any of the gateways that received that uplink.

The first gateway in the list is not the one with the best SNR/RSSI values (unless accidental).
The currently displayed SNR and RSSI values are not representative and hence practically useless (bug).

The best SNR/RSSI pair from all gateways that received the uplink shall be displayed instead.

#### Steps to Reproduce

Just check Console > Applications > Live data for uplink messages that were received by multiple gateways.
Compare SNR and RSSI values listed in the Data preview field with values in the JSON details.

#### What do you see now?

SNR and RSSI values from first gateway in the list.

#### What do you want to see instead?

SNR and RSSI values from the gateway with the best SNR/RSSI value pair.

#### Environment

Not relevant.

#### How do you propose to implement this?

Determine which gateway shows the best SNR/RSSI value pair and show those SNR and RSSI values instead.

The SNR and RSSI values should be from the same gateway of course.

I'm not sure how to compare SNR/RSSI combinations, but the (RF) experts will probably know how to determine ranking.

#### How do you propose to test this?

Just verify in the console.

#### Can you do this yourself and submit a Pull Request?

No.

**Comment by sanijs** [comment]
I have the exact same problem when having multiple gateways at our locations

![console](https://user-images.githubusercontent.com/84848497/148388543-03e26d22-5635-416a-98fc-ac89e1b35444.JPG)

![rx_data](https://user-images.githubusercontent.com/84848497/148388599-ef23c81b-5f30-412a-8369-2b7b4e2755bc.JPG)

It would also make it easier when forwarding the data to one's backend, because then you don't have go to through your entire rx_metadata array to find out which one is the best.

It would make it easier if was sorted after the best SNR/RSSI (the same algorithm used for making a downlink), so you only have to get uplink_message.rx_metadata[0]

**Comment by kschiffer** [comment]
Thanks for filing this issue @lnlp!

@ryaplots can you schedule this for one of the upcoming milestones. It should be a simple fix.

**Comment by ryaplots** [comment]
Is it possible to sort the list of gateways by the SNR/RSSI value pair in the backend? @adriansmares / @htdvisser

**Comment by htdvisser** [comment]
We're not going to do that. Consumers should not rely on RX metadata being in any particular order. If consumers want to do some aggregation to find the min/avg/max SNR/RSSI/etc. they should do that themselves.

**Comment by lnlp** [comment]
@kschiffer @ryaplots @htdvisser 

This issue was closed for what reason?, because already planned for/implemented in v3.18.1?

Is this now implemented by #5242?

#5242 is about SNR only. Is 'best SNR' representative for 'best RSSI/SNR' combination?

**Comment by kschiffer** [comment]
For technical reasons, we have to resort to the highest SNR for the time being. The pair calculation is not trivial, since RSSI is not a normalized measure and can vary depending on the gateway antenna. Also in the backend, we are currently mainly using the highest SNR to determine gateways for downlinks. This calculation will be updated with a more precise algorithm at a later stage at which point we can reconsider the Consoles calculation as well.

> because already planned for/implemented in v3.18.1?

Yes. Keep in mind that merging does not mean that the feature is immediately active in our deployments, but will be updated as per our release and deployment schedule in the days after the release.
