### ISSUE TITLE
Validate entities by field mask

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#51]
**Summary:** 

This issue handles logical validation process of 
- checking a fieldmask on a message, 
- applying the fieldmask and then 
- validating only the fields that are remaining in the message once the fieldmask is applied.

**Why do we need this?**

Proto Messages need to be validated in two cases. 
 - When they are used in RPCs by clients.
 - When they are stored in the JS/AS/NS registries.

In both cases, the fieldmask must be used in the validation process.

**What is already there? What do you see now?**

Fieldmasks are not validated. 

**What is missing? What do you want to see?**

 - [ ] 1. Check that the provided fieldmask is valid.
 - [ ] 2. Apply the fieldmask on the message.
 - [ ] 3. Validate the remaining fields in the message. 

This issue only implements a _generic method_ which can be called by any rpc/registry-function and pass the corresponding fieldmask. 

These methods will be actually _used/called_ in rpcs/registry in #69 

**How do you propose to implement this?**

1. Is a simple check. 
It's a simple intersection function to check if the provided fieldmask is a subset of the supported fieldmask for that method.
 
2. Is easy since we already have `SetFields()`.

3. The validator would be modified to `Validate(paths []string)` and only the items specified in `paths` would be considered.

**What can you do yourself and what do you need help with?**

I can implement this but needs a bit more discussion/inputs on the last point. 

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/1440 by @KrishnaIyer

**Comment by rvolosatovs** [comment]
I added https://github.com/TheThingsIndustries/protoc-gen-fieldmask/issues/21 - please look at the proposal.
I think it makes much more sense to just extend our existing solution for this, which is very straight-forward.
The only difference in implementation compared to `SetFields` is that the terminal fields shall be validated instead of copied. The overall structure and approach are exactly the same. It should be also much easier to do that than to patch and maintain forks of existing solutions not designed for our use case and try to adapt them in various hacky ways.
There are not many things we need to validate anyway and we can take inspiration from the existing validators, possibly even reuse something.
As a must we only need:
- Numerical value ranges
- String/Slice length
- Nil/Non-nil checking
- Enum validation

**Comment by rvolosatovs** [comment]
Here's an example of generated code with the new plugin: https://github.com/rvolosatovs/lorawan-stack/commit/9d36c19dda21e82c01a32c2626285f2fcb93f4c2
All https://github.com/lyft/protoc-gen-validate rules are supported
