### ISSUE TITLE
The network server does not respond to DeviceTimeRequest if the command is accompanied by a TXParamSetupAns

### ISSUE THREAD

**Issue by Achichig** [TheThingsNetwork/lorawan-stack#5608]
### Summary

In the case where a modem has to send a TxParamSetupAnswer and a DeviceTimeRequest, the NS sees the commands but does not answer the DeviceTimeRequest.  

### Steps to Reproduce

I saw this bug using AS923 GRP4 frequency plan, Lorawan spec 1.0.4, RP2 v1.0.3.

1. Send payload (frm_payload) 0x09 0D to NS (0x09 for TxParamSetupAns and 0x0D for DeviceTimeRequest) on port 0 (without fopts)

### Current Result

In the image below, the fcnt 6 message corresponds to TxParamSetupAns and DeviceTimeRequest (as we can see in the decrypted payload lower). We can see that following this uplink, the NS does not enqueue any downlink DeviceTimeAnswer .

![image](https://user-images.githubusercontent.com/101577545/179470037-b505f5f3-60b8-4015-bc4c-6d8fee5d62e1.png)

![image](https://user-images.githubusercontent.com/101577545/179470115-e289bd69-e277-4eee-95ed-32bb06ad400b.png)

### Expected Result

I am expecting the NS to answer to DeviceTimeRequest even if this mac command is combined with a TxParamSetupAnswer

### Deployment

The Things Stack Enterprise (self-hosted)

### The Things Stack Version

3.19.1

### Contributing

- [ ] I can help by doing more research.
- [ ] I can help by implementing a fix after the proposal above is approved.
- [X] I can help by testing the fix before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by adriansmares** [comment]
Can you please provide an event stream in JSON format with verbose logging enabled ? You may share those via email (`adrian.mares@thethingsindustries.com`) if you consider that they contain sensitive data.

Note that you should never rely on having a Network Server response in the subsequent downlink - that's only the happy case. A non exhaustive list of things that can go wrong:
- The uplink containing the requests may be lost over the air or due to latency arrive too late for RX1/RX2.
- The downlink containing the response may be lost over the air or due to latency arrive too late for RX1/RX2.
- The MAC response may not fit the downlink - the NS will set the `FPending` to `true` but the end device still needs to send the unanswered requests in the subsequent uplink that opens a new receive window.

I can't tell only from the provided information why the NS did not generate a response+downlink, but I do think this bug report may be valid.

**Comment by Achichig** [comment]
Hello adriansmares,

Thanks for your answer, I will send you the verbose logs by email right now

**Comment by adriansmares** [comment]
Thanks for the logs - I have found the issue here. It is interesting.

---

In TTS we have the concept of pending requests - MAC command requests which are awaiting for a response from the end device. The flow is particularly easy:
1. An end device sends an uplink.
2. We walk through the MAC commands from the end device and check if the responses handle any old pending requests. These are removed from the pending requests list.
2. If there are any pending requests left, we log them in the stack Console with a warning (this should become an event instead).
3. We flush the pending requests.
4. We generate new pending requests if the desired and current state of the end device has a drift. We schedule a downlink with these requests.
5. Goto 1.

This is very much in line with what the 1.0.4 spec has in mind, with a request-response flow in which a transmitter has to re transmit a request if he wants a new response. The twist is that `RXParamSetupReq`, `RXTimingSetupReq`, `TXParamSetupReq` and `DlChannelReq` do not work like this.
<img width="780" alt="image" src="https://user-images.githubusercontent.com/36161392/179527835-faa3339e-330e-424a-9727-1535fdd6e9f0.png">

The commands mentioned above actually will have the `*Ans` attached to the uplinks until the NS schedules a downlink to the end device:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/36161392/179528011-a839b302-da96-458d-91f5-592cc8a0abfe.png">
<img width="968" alt="image" src="https://user-images.githubusercontent.com/36161392/179528142-a6cc40f6-cd50-400f-9357-3f4798f575fa.png">
<img width="957" alt="image" src="https://user-images.githubusercontent.com/36161392/179528376-8bd1f32a-8bdc-43b9-948c-ff8ba79edcdb.png">
<img width="969" alt="image" src="https://user-images.githubusercontent.com/36161392/179528556-85079dc3-1a07-4079-bfcd-f7b911f4b080.png">

---

In this issue, via private logs, I've seen that the end device keeps sending the `TxParamSetupAns` over multiple uplinks until a downlink is sent.

---

The Network Server is not really compatible right now with the fact that these `*Ans` commands will be resent multiple times. We will see an `*Ans` without a pending request and drop the remaining MAC commands:
https://github.com/TheThingsNetwork/lorawan-stack/blob/5047fe7f74def34c2c42ac0516aa9b3ac323736e/pkg/networkserver/mac/mac.go#L51-L65
https://github.com/TheThingsNetwork/lorawan-stack/blob/5047fe7f74def34c2c42ac0516aa9b3ac323736e/pkg/networkserver/grpc_gsns.go#L580-L583

---

What needs to be done here: `handleMACResponse` / `handleMACResponseBlock` should have a parameter `allowNotFound` which basically handles these 'response retransmissions'. `RXParamSetupAns`, `RXTimingSetupAns`, `TXParamSetupAns`, `DlChannelAns` should use it, while other commands should continue to disapprove unrequested responses.

**Comment by johanstokking** [comment]
Yes indeed. These are sticky answers.

What do you propose will happen if there's an invalid answer? Drop the remaining MAC commands still? What does this mean for the end device state going forward?

**Comment by adriansmares** [comment]
> What do you propose will happen if there's an invalid answer? Drop the remaining MAC commands still? What does this mean for the end device state going forward?

I can think of at least 3 error types:
- Invalid because the contents of the MAC buffer do not make sense (i.e. we have an unmarshaling error)
  - Then we probably should drop the whole MAC buffer - we have no reasons to believe that its contents are really valid anymore
  - This should be an end device event instead of a stack warning
- Invalid because the request did not exist
  - We probably should not mutate the MAC state, but we can continue to consume the rest of the commands
  - We may want to emit an event if the answer is not meant to be sticky
- Invalid because the MAC command handler (`Handle*Ans`) failed
  - None of the handlers actually return `err` that is not `nil` - the only special case is `HandleRekeyInd` which really should panic probably

All 3 of the above may signal the fact that the MAC state is de-synchronized, but I cannot say what we should do at that point.

Users need to be made more aware of the fact that the NS cannot communicate properly with their end device, but killing the communication completely if an anomaly is detected would be too harsh: remember the 'would you swear with your right hand on your heart that you allow only certified end devices to be registered' - it's a wild west out there when it comes to end device stacks.

**Comment by johanstokking** [comment]
> All 3 of the above may signal the fact that the MAC state is de-synchronized, but I cannot say what we should do at that point.
> 
> Users need to be made more aware of the fact that the NS cannot communicate properly with their end device, but killing the communication completely if an anomaly is detected would be too harsh:

Yes, fully agreed. Also I think indeed for reasons 1 and 2 we'll want an event.
