### ISSUE TITLE
more CoyenneLPP Types

### ISSUE THREAD

**Issue by mcenderdragon** [TheThingsNetwork/lorawan-stack#5939]
### Summary

Many CayenneLPP libs (like the [Arduino lib](https://github.com/ElectronicCats/CayenneLPP)) support lots of different types, like timestamp. The TTN Console does only support very few, and the error messages are VERY bad (invalid data, when it could said unknown type 133).

### Current Situation

only very few types are supported and types like time, pressure, lux arent.

### Why do we need this? Who uses it, and when?

CayenneLPP is an easy< way to send data that supports many types out of the box. it would be kind of stupid if everybody had to reimplment everythign in JS beucase TTN is not supporting all the types.

### Proposed Implementation

add the new types to https://github.com/TheThingsNetwork/lorawan-stack/blob/11e68eaaeb12121b2c032a24e50c6acbdfc6ce94/pkg/messageprocessors/cayennelpp/cayennelpp.go

### Contributing

- [ ] I can help by doing more research.
- [X] I can help by implementing the feature after the proposal above is approved.
- [ ] I can help by testing the feature before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by johanstokking** [comment]
@mcenderdragon we follow the [official documentation](https://docs.mydevices.com/docs/lorawan/cayenne-lpp#data-types). There's a [warning](https://github.com/ElectronicCats/CayenneLPP#-warning-) on the repository of the library you are using.

I would advise working with myDevices to extend the data types of CayenneLPP so that we support them.

I would like to avoid getting on the sliding edge of supporting non-official data types. If users start relying on those, and protocol owner myDevices defines them in a different way, we get ourselves in an irreversible mess.

So, let's switch my constructive side;

Alternative 1: I'm okay with a **CayenneLPP (ElectronicCats)** derivative, that would be a separate message processor.

Alternative 2: implement a JavaScript payload codec to decode your favorite CayenneLPP flavor into an object that looks like what you want to have.
