### ISSUE TITLE
Recover downlink queue in case of replay attack or failed rejoin

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsNetwork/lorawan-stack#594]
#### Summary

NS and AS need to recover session in case of replay attack or failed rejoin. 

#### Why do we need this?

To improve security and support rejoin flow

#### What is already there? What do you see now?

NS notifies AS that downlink queue is invalidated once join-accept is received from JS and queued(not scheduled).

#### What is missing? What do you want to see?

If the device sends an uplink using the old session context, NS shall inform AS that the queue is invalidated once again and the old security context is to be recovered.

#### How do you propose to implement this?

Add `ApplicationSessionRecovery` type or similar, which would be sent to AS once the old session context is to be recovered.

#### Can you do this yourself and submit a Pull Request?

@johanstokking is responsible for AS, hence I assign him. I will assist with the NS part.

**Comment by johanstokking** [comment]
@rvolosatovs If I understand this correctly, then AS already supports this.

On join-accept, AS puts the new session in `pending_session`; it doesn't touch the `session`. Since the NS discards the downlink queue on join-accept, AS does proactively recalculate the downlink queue with the new session.

On uplink, if the uplink message's session is not `session` (i.e. it is `pending_session` or it is an unknown session), there's session switch or recovery respectively. That results in downlink queue recalculation.

Re-assigning to you as I believe AS handles this correctly and we don't need new events.
