### ISSUE TITLE
LoRa ALCS Improvements

### ISSUE THREAD

**Issue by cvetkovski98** [TheThingsNetwork/lorawan-stack#6105]
### Summary

Follow up #6090 with some improvements:
- [ ] Add observability
  - [ ] Use `WithCause(err)` when propagating package errors
  - [ ] Use `evtPackageFail` event to signal package failures
  - [ ] Use events to give insight into the data after and before serialization (verbose events)
- [ ] Update CHANGELOG.md
- [ ] Fix typos

### Current Situation

We have no error trace when an error occurs in the `alcsync-v1` package and it is difficult to inspect the communication between The Stack and the end devices.

### Why do we need this? Who uses it, and when?

It would help in debugging when something goes wrong.

### Contributing

- [X] I can help by doing more research.
- [X] I can help by implementing the feature after the proposal above is approved.
- [X] I can help by testing the feature before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).

**Comment by adriansmares** [comment]
Some other useful things to look into:
1. We would benefit from some events which occur when a request arrives, and when we generate a response. The event body should be the request/response itself. We do this a lot in the Network Server. Things to look at:
- How MAC commands are defined in the API:
https://github.com/TheThingsNetwork/lorawan-stack/blob/2ebeaf5073b218b79af1157fd1430b5c1b72134e/api/lorawan.proto#L541-L740
This will be needed in order to allow the request/responses to be marshalled properly in the event data. You can create an `applicationserver_integrations_alcsync.proto` just for this.
- The NS has some utility functions that you may be interested in implementing for your own request/responses:
https://github.com/TheThingsNetwork/lorawan-stack/blob/2ebeaf5073b218b79af1157fd1430b5c1b72134e/pkg/networkserver/mac/observability.go#L25-L83
This will make defining new events easier. The actual definition sites become then:
https://github.com/TheThingsNetwork/lorawan-stack/blob/2ebeaf5073b218b79af1157fd1430b5c1b72134e/pkg/networkserver/mac/link_adr.go#L30-L43
- Deferred event publication:
https://github.com/TheThingsNetwork/lorawan-stack/blob/2ebeaf5073b218b79af1157fd1430b5c1b72134e/pkg/networkserver/grpc_gsns.go#L967-L975
This sounds a lot more sophisticated than it actually is. Instead of just doing `events.Publish` from the request/response handling code, return the new events from the handlers and just publish everything at once. It's a bit more efficient for our underlying events backend.
