### ISSUE TITLE
Payload formatters

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#71]
**Summary:** 
The console needs a way to manage payload formatters on both device and application level.

**Why do we need this?**
A simplified implementation is part of the Console MVP, fully working version for production.

**What is already there? What do you see now?**
- Implementation in v2
- Code editor component

**What is missing? What do you want to see?**
- Wireframes (?)
- Implementation
  - [ ] Select input
  - [ ] The page itself

1. Supported formatters : none, javascript, grpc service, cayennelpp.
    1.1 For the javascript formatter we need a code editor, https://github.com/securingsincity/react-ace should do the job (it is used in v2)
    1.2 For the grpc service formatter we need only a single input for the service address
    1.3 The rest dont need any additional inputs
2. The javascript formatter has only two functions - encoder and decoder

**How do you propose to implement this?**
Similar to the v2 payload formatter, but without the tester (for MVP)

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/1379 by @kschiffer

**Comment by bafonins** [comment]
Will be a part of the Application Link page, see https://github.com/TheThingsNetwork/lorawan-stack/issues/214

**Comment by kschiffer** [comment]
Forwarding for completeness ([original](https://github.com/TheThingsIndustries/lorawan-stack/issues/1379#issuecomment-454456244) from @bafonins ):
After a quick discussion with @johanstokking, we agreed that the resulting page in the v3 console will be similar to the one in the v2 console. However, there are a couple of changes for the Console MVP:
1. No payload tester
2. Supported formatters : `none`, `javascript`, `grpc service`, `cayennelpp`.
  2.1 For the javascript formatter we need a code editor, https://github.com/securingsincity/react-ace should do the job (it is used in v2)
  2.2 For the grpc service formatter we need only a single input for the service address
  2.3 The rest dont need any additional inputs
3. The javascript formatter has only two functions - encoder and decoder

**Comment by bafonins** [comment]
> Will be a part of the Application Link page, see #214

Reopening since the Application Link covers only the bare minimum of linking.

**Comment by bafonins** [comment]
<img width="685" alt="screen shot 2019-03-07 at 16 06 58" src="https://user-images.githubusercontent.com/16374166/53966245-19777300-40f3-11e9-9edb-13bb9c6ba508.png">

I can imagine the top-level tabs can cause problems on the Device Overview page:
<img width="955" alt="screen shot 2019-03-07 at 16 08 21" src="https://user-images.githubusercontent.com/16374166/53966339-47f54e00-40f3-11e9-8a99-2f7ae1ca1527.png">

Having 3 levels of tabs i definitely not a good solution.

cc @kschiffer(suggestions?) @htdvisser

**Comment by kschiffer** [comment]
We shouldn't use tabs to select the payload format type (JS, GRPC Service, CayenneLPP) anyway because a tab is not a proper input element. Yet the user needs to select an option here explicitly, which is why I used radio-buttons instead.
![payload formatters](https://user-images.githubusercontent.com/5710611/54026268-8e9f8280-419d-11e9-9462-f6a9aa823d68.png)
For switching to encoder or decoder, we can use tabs, because it is just changing what the user wants to see/edit from the formatter and the integration into the form makes it scoped enough to not interfere with the other tabs.

**Comment by kschiffer** [comment]
For application level:
![application payload formatter](https://user-images.githubusercontent.com/5710611/54029177-d2978500-41a7-11e9-9b87-39fb2efa9719.png)

When application is not linked:
![application payload formatter no link](https://user-images.githubusercontent.com/5710611/54029191-dc20ed00-41a7-11e9-91db-7f21228cbc58.png)

Feedback welcome.

**Comment by htdvisser** [comment]
1. We should use the correct terminology. These are **message payload formatters**
2. You can configure two formatters: one for uplink and one for downlink. It is possible to use different formatters for uplink and downlink.
3. Each configuration of a formatter consists of
  A. The "Formatter" that can be one of `NONE`, `GRPC_SERVICE`, `JAVASCRIPT`, `CAYENNELPP`. I don't know why `REPOSITORY` was omitted in https://github.com/TheThingsNetwork/lorawan-stack/issues/71#issuecomment-469720772 (@johanstokking?)
  B. The parameter (editor for `JAVASCRIPT`, a regular input for `GRPC_SERVICE`, nothing for the others)

As a result of (2) I'm first of all not sure that the v2 terms "Encoder"/"Decoder" should be used. Secondly, we should split uplink and donwlink parts and put them both on the page. It's perfectly resonable to think that someone would use CayenneLPP for uplink, and JavaScript for downlink.

![54029177-d2978500-41a7-11e9-9b87-39fb2efa9719](https://user-images.githubusercontent.com/181308/54032409-d3351900-41b1-11e9-8ccf-a70f6be6b354.png)

We can get rid of the "Remove Formatter", because removing it would be achieved by setting it to "none".

**Comment by kschiffer** [comment]
Thanks for the input! In that case, listing the uplink and downlink formatter options below each other is indeed better. I was experimenting briefly with using tabs to split uplink and downlink messages but that will result in unnecessary workload and also possibly confusing UX in the device context because there would be two tabs right below each other, as @bafonins pointed out. Also, the form is at this point lean enough to show both.
We can adapt the design progressively once we add functionality then.

**Comment by johanstokking** [comment]
Indeed `REPOSITORY` is a valid option.
