### ISSUE TITLE
Send Emails

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#72]
**Summary:** 

The Identity Server should send (at least essential) emails.

**Why do we need this?**

Without it, we can't do contact info validation, forgot password functionality.

**What is already there? What do you see now?**

The `email` package, as well as some kind of template registry.

**What is missing? What do you want to see?**

The actual email messages.

**How do you propose to implement this?**

I think we should start with the essential emails:

- [x] Welcome email for new users, including contact info validation.
- [x] Password Recovery email
- [x] Entity Contact Info Validation email

And then continue with "notification" emails such as:

- [x] Password Changed
- [ ] User Email Changed
- [x] Collaborator added/updated
- [x] API Key created/updated

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/1395 by @htdvisser

**Comment by htdvisser** [comment]
Reopening this, since there are still a bunch of TODOs left in the codebase referring to this issue:

https://github.com/TheThingsNetwork/lorawan-stack/blob/fe5b1d5bd568613ebe3549e841d2c8c7a39d00e3/pkg/identityserver/invitation_registry.go#L62

https://github.com/TheThingsNetwork/lorawan-stack/blob/71e4ef8ad894c21bb5069b9ec754b50640362390/pkg/identityserver/user_registry.go#L204

https://github.com/TheThingsNetwork/lorawan-stack/blob/71e4ef8ad894c21bb5069b9ec754b50640362390/pkg/identityserver/user_registry.go#L388

https://github.com/TheThingsNetwork/lorawan-stack/blob/fe135f4b4b6a11b9b8f60ab968b9928d080aca75/pkg/identityserver/client_registry.go#L254
