### ISSUE TITLE
Support Basic Station CUPS protocol

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#75]
**Summary:** 

Support the [Basic Station CUPS protocol](https://doc.sm.tc/station/cupsproto.html).

References #1412.

**Why do we need this?**

To configure the LNS (GS) endpoint to Basic Station gateways.

**What is already there? What do you see now?**

Nothing.

**What is missing? What do you want to see?**

Expose the CUPS endpoint in a service next to or in the Identity Server.

This is simply one HTTP request/response. This is a non-cluster specific call, i.e. gateways anywhere in the world connect to a provisioning service.

**How do you propose to implement this?**

1. A micro-service that runs in the cluster of the IS, and uses cluster authentication to the IS. I'm also fine with exposing this endpoint directly in IS, as some kind of module/registered endpoint. @htdvisser ideas?
2. There is TLS server authentication with a trust that is configured in the gateway. That is, we provide a Let's Encrypt root or our own CA to the gateways. Our CUPS server should either expose a TLS server itself (not my preference) or work behind a proxy that does TLS termination (my preference, i.e. GCP Load Balancer – I tested this already with Let's Encrypt and that works with the Mini Hub)
3. The gateway authenticates [with a client token](https://doc.sm.tc/station/authmodes.html#tls-server-authentication-and-client-token). Semtech gives us a list of all EUIs + client tokens. This client token does not follow our API key format and we cannot customize this. @htdvisser do we support custom formatted API keys, or should the CUPS service have its own registry?

**What can you do yourself and what do you need help with?**

I'll see how far I get with this, but I may re-assign @htdvisser after his holiday.

----

Original issue: https://github.com/TheThingsIndustries/lorawan-stack/issues/1413 by @johanstokking

**Comment by htdvisser** [comment]
Alright, so considering that I don't have time to finish this up before I go skiing, here's a quick update on the current state.

My implementation so far is in branch [`feature/75-cups`](https://github.com/TheThingsNetwork/lorawan-stack/compare/feature/75-cups). I initially implemented it as part of the Identity Server, but then decided to split it out into a separate component, because it's likely that multiple CUPS servers will talk to the same Identity Server, or that a single CUPS server talks to multiple Identity Servers.

CUPS code is in `pkg/basicstation/cups`:

- `messages.go` is for encoding/decoding the JSON UpdateInfoRequest and the binary UpdateInfoResponse. 
- `server.go` is the general server setup. A `cups.Server` is instantiated from a `cups.ServerConfig`, and from `cups.Option`s. In order to support multiple ISs behind the CUPS, the auth, registry client and access client getters depend on the context. For testing, you can override the `registry`/`access` fields of the Server struct.
- `server.go` also contains some utilities, feel free to move those to different files. The `parseAddress` utility helps us transform the GS address (which can have several forms) into a proper LNS address. `getTrust` connects to a GS in order to get its root certificate so that the CUPS can send it (as "trust") to the gateway. In the future we may have to add support for GSs behind a firewall (that the CUPS can't reach), but that's not MVP.
- `update_info.go` contains the `update-info` handler. If configured, gateways that aren't found, can be registered the first time they are seen. After we have a Gateway, we use the GatewayServerAddress for LNS, and extensively use the Attributes to store additional CUPS data. Firmware updates and CUPS address updates are currently disabled.

The Stack can be started with CUPS enabled with: `go run ./cmd/ttn-lw-stack start is cups --cups.owner-for-unknown.account-type user --cups.owner-for-unknown.id admin --cups.owner-for-unknown.api-key NNSXS.XXX.YYY`. 

You may also have to supply `--grpc.allow-insecure-for-credentials`, not 100% sure about that.

Next, you're going to have to set up https://github.com/lorabasics/basicstation according to their instructions. Inside the `examples/live-s2.sm.tc` you have to execute the following before running `station` (or after `make clean`):

```sh
echo "https://macbook.htdvisser.dev:8885" > cups-boot.uri
openssl x509 -inform PEM -outform DER -text -in $GOPATH/src/go.thethings.network/lorawan-stack/cert.pem -out cups-boot.trust
echo "Authorization: xxyyzz" > cups-boot.key
rm cups-boot.crt
```

Make sure that the hostname in `cups-boot.uri` actually resolves to the machine where you run CUPS. In Docker for Mac `host.docker.internal` sometimes works for this.
Also make sure that `cups-boot.key` uses CRLF line endings.
