### ISSUE TITLE
Split the MQTT server out from the application code

### ISSUE THREAD

**Issue by proffalken** [TheThingsNetwork/lorawan-stack#87]
**Summary:** 
At present, the Gateway Server also acts as an MQTT server, receiving all the messages directly from the gateways ( https://github.com/TheThingsNetwork/lorawan-stack/tree/master/pkg/gatewayserver/io/mqtt ).

In order to ensure that this project is able to scale past a single node, it would be preferable to turn the Gateway Server into an MQTT client, and hand over management of message queues etc. to a dedicated tool for the task such as Mosquitto or RabbitMQ (with the MQTT plugin enabled) 

**Steps to Reproduce:** 
Spin up a new stack, if there is an existing MQTT server running on the same host, the stack will fail to launch with a "port already in use" error

**What do you see now?**
As above, the MQTT Server is contained within the application code

**What do you want to see instead?**
The ability to choose a carrier-grade MQTT server instead of relying on the embedded MQTT server in the gateway code itself.

**How do you propose to implement this?**
Work with others to convert the code in the Gateway server from an MQTT server to an MQTT Client.

**Environment:**
Any

**What can you do yourself and what do you need help with?**
I can advise on design etc, I would need help to write the code itself.

**Comment by johanstokking** [comment]
Thanks for reporting. This is by design; same for the Application Server.

One reason to expose MQTT in GS is portability, i.e. no dependency on another service. Another reason is that the gateway connection including scheduling and conflict mitigation, duty-cycle enforcement and statistics are currently in-memory in GS, making it a 1-1 stateful connection. An MQTT server in between would not solve that. 

Instead, the core components themselves are designed for N by replicating the GS instances and putting a load balancer in front. The implementation and wiring of that is not (yet) contributed under Apache 2.0 by TTI.
